// <auto-generated />
using MVC_Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Database.Migrations
{
    [DbContext(typeof(MVC_DbContext))]
    [Migration("20221115151122_Seeding People to DB")]
    partial class SeedingPeopletoDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVC_Data.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Gothenburg",
                            Name = "Siavash Gosheh",
                            PhoneNumber = "xxxx-xxx666"
                        },
                        new
                        {
                            Id = 2,
                            City = "Central Pennsylvania",
                            Name = "Maxwell T Bird",
                            PhoneNumber = "Mr. Max Tv @ Youtube"
                        },
                        new
                        {
                            Id = 3,
                            City = "Gdansk",
                            Name = "Nergal",
                            PhoneNumber = "666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
